name: Convert Notebooks to HTML

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install nbconvert plotly

      - name: Convert .ipynb to HTML
        run: |
          mkdir -p docs
          for nb in notebooks/*.ipynb; do
            jupyter nbconvert "$nb" --to html --output-dir docs
          done

      - name: Add index.html
        run: |
          echo '<!DOCTYPE html><html><head><title>Notebook Index</title></head><body><h1>Notebook Gallery</h1><ul>' > docs/index.html
          for file in docs/*.html; do
            fname=$(basename "$file")
            if [ "$fname" != "index.html" ]; then
              echo "<li><a href='$fname'>$fname</a></li>" >> docs/index.html
            fi
          done
          echo '</ul></body></html>' >> docs/index.html

      - name: Commit & Push generated HTML
        env:
          GH_PAGES: ${{ secrets.GH_PAGES }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "Update HTML outputs" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAGES}@github.com/${{ github.repository }}.git HEAD:main




