name: Convert Notebooks to HTML

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install nbconvert plotly

      - name: Convert .ipynb to HTML
        run: |
          mkdir -p docs
          for nb in notebooks/*.ipynb; do
            jupyter nbconvert "$nb" --to html --output-dir docs
          done

      - name: Add index.html
        run: |
          echo '<!DOCTYPE html>
          <html lang="en" class="dark">
          <head>
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>Notebook Gallery</title>
            <script src="https://cdn.tailwindcss.com"></script>
          </head>
          <body class="bg-gray-900 text-white min-h-screen font-sans p-8">
            <h1 class="text-3xl font-bold mb-6">📘 Notebook Gallery</h1>
            <ul class="space-y-4">
          ' > docs/index.html

          for file in docs/*.html; do
            fname=$(basename "$file")
            if [ "$fname" != "index.html" ]; then
              echo "<li><a class='text-blue-400 hover:underline' href='$fname'>$fname</a></li>" >> docs/index.html
            fi
          done

          echo '</ul>
          </body>
          </html>' >> docs/index.html

      - name: Commit & Push generated HTML
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update HTML outputs
          branch: gh-pages
          file_pattern: docs/*
          commit_user_name: github-actions
          commit_user_email: github-actions@github.com
          push_options: '--force'
          token: ${{ secrets.GH_PAGES }}






